[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/pi/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
    #Tailscale addresses
    100.90.238.15
    100.122.89.103
    100.127.12.15
    100.73.116.4
    100.99.198.95
    fd7a:115c:a1e0::a601:ee11
    fd7a:115c:a1e0::da01:7b0b
    fd7a:115c:a1e0::aa01:7404
    fd7a:115c:a1e0::d601:c10
    fd7a:115c:a1e0::3501:5968
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz
	klippylyzer.github.io

[file_manager]
# post processing for object cancel. Not recommended for low resource SBCs such as a Pi Zero. Default False
enable_object_processing: True

[octoprint_compat]

[history]

# this enables moonraker announcements for mainsail
[announcements]
subscriptions:
    mainsail

[update_manager]
channel: dev
refresh_interval: 168
enable_auto_refresh: True


[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: ~/mainsail
[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main